config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update, :destroy]
  resources :questions, only: [:index, :create, :edit, :update, :destroy]

  get 'backend/index' => 'backend#index'

  get 'backend/answers_by_result'              => 'backend#answers_by_result'
  get 'backend/answers_by_question_and_result' => 'backend#answers_by_question_and_result'
  get 'backend/answers_by_result_and_month'    => 'backend#answers_by_result_and_month'

  get 'users/publish'   => 'users#publish'
  get 'users/unpublish' => 'users#unpublish'

  get  'questionarios/:slug'         => 'answers#new',    as: "view_questionaire"
  post 'questionarios/:slug/create'  => 'answers#create', as: "save_questionaire"
  get  'questionarios/:slug/success' => 'answers#show',   as: "finish_questionaire"

  root 'backend#start'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  enum result: [:poor, :fair, :good]
  RESULT_NAMES = %w(Insatisfeito(a) Neutro(a) Satisfeito(a))

  before_validation :set_user

  validates :user, :question, :result, presence: true

  protected

  def set_user
    self.user ||= question.user if question.present?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  layout "answers"

  before_action :set_user, only: [:new, :create, :show]

  def new
    @questions = @user.questions.order(:position).all
  end

  def create
    if params[:answers].present?
      params[:answers].each do |question_id, result|
        Answer.create! question: Question.where(id: question_id).first, result: result
      end
    end

    redirect_to finish_questionaire_path(slug: @user.slug)
  end

  private

  def set_user
    @user = User.where(slug: params[:slug]).first

    if @user.blank?
      redirect_to root_path
      return false
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/new.html.erb
<% if @user.questionaire_published? %>
  <%= form_tag save_questionaire_path, class: "form-horizontal" do %>
    <% @questions.each do |question| %>
      <div class="question panel panel-primary">
        <div class="panel-heading text-bold"><%= question.statement %></div>

        <div class="panel-body">
          <div class="row">
            <% Answer.results.keys.each do |result| %>
              <div class="answer col-lg-4 col-md-4 col-sm-4 col-xs-4">
                <%= radio_button_tag "answers[#{question.id}]", result %>
                <%= label_tag "answers_#{question.id}_#{result}", image_tag("#{result}.png") %>
                <br/>
                <%= Answer::RESULT_NAMES[Answer.results[result.to_sym]] %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="actions">
      <%= button_tag(type: "submit", class: "btn btn-success btn-lg text-bold") do %>
        <i class="fa fa-check"></i> Finalizar
      <% end %>
    </div>
  <% end %>
<% else %>
  <h1 id="standalone-message">
    Este questionário está em manutenção agora.
    <br/>
    Por favor, volte mais tarde.
  </h1>
<% end %>

app/views/answers/show.html.erb
<h1 id="standalone-message">
  Recebemos as suas respostas.
  <br/>
  Muito obrigado!
</h1>