config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update, :destroy]
  resources :questions, only: [:index, :create, :edit, :update, :destroy]

  get 'backend/index' => 'backend#index'

  get 'backend/answers_by_result'              => 'backend#answers_by_result'
  get 'backend/answers_by_question_and_result' => 'backend#answers_by_question_and_result'
  get 'backend/answers_by_result_and_month'    => 'backend#answers_by_result_and_month'

  get 'users/publish'   => 'users#publish'
  get 'users/unpublish' => 'users#unpublish'

  get  'questionarios/:slug'         => 'answers#new',    as: "view_questionaire"
  post 'questionarios/:slug/create'  => 'answers#create', as: "save_questionaire"
  get  'questionarios/:slug/success' => 'answers#show',   as: "finish_questionaire"

  root 'backend#start'

end

app/views/layouts/answers.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Responda Nossa Pesquisa De Satisfação Online e Nos Ajude a Melhorar!"/>
    <meta name="author" content="Mário Marroquim"/>
    <meta property="og:locale" content="pt_BR"/>
    <meta property="og:url" content="<%= url_for(view_questionaire_path(slug: @user.slug, only_path: false)) %>"/>
    <meta property="og:title" content="Pesquisa De Satisfação Online - <%= current_user.company %>"/>
    <meta property="og:site_name" content="<%= @user.company %>"/>
    <meta property="og:description" content="Responda Nossa Pesquisa De Satisfação Online e Nos Ajude a Melhorar!"/>
    <meta property="og:image" content="<%= URI(request.url) + @user.logo.url %>"/>
    <meta property="og:type" content="website"/>

    <title><%= @user.company %> - Pesquisa De Satisfação Online</title>

    <%= favicon_link_tag "favicon.ico", :rel => "shortcut icon" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <link href="http://getbootstrap.com.br/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="answers">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
          <div id="logo">
            <%= link_to image_tag(@user.logo.url), view_questionaire_path(slug: @user.slug) %>
          </div>

          <p id="header"><%= @user.questionaire_header %></p>

          <hr/>

          <%= yield %>

          <hr/>

          <p id="footer"><%= @user.questionaire_footer %></p>

          <div id="sharing" class="text-bold">
            <p>Compartilhe esta página:</p>
            <span class="st_facebook_large" displayText="Facebook"></span>
            <span class="st_whatsapp_large" displayText="WhatsApp"></span>
            <span class="st_twitter_large" displayText="Tweet"></span>
            <span class="st_linkedin_large" displayText="LinkedIn"></span>
            <span class="st_googleplus_large" displayText="Google +"></span>
            <span class="st_pinterest_large" displayText="Pinterest"></span>
            <span class="st_email_large" displayText="Email"></span>
          </div>
        </div>
      </div>
    </div>

    <script src="http://getbootstrap.com.br/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="Sistema Para Pesquisa De Satisfação Online. Plano gratuito!"/>
    <meta name="author" content="Mário Marroquim"/>
    <meta property="og:locale" content="pt_BR"/>
    <meta property="og:url" content="<%= url_for(view_questionaire_path(slug: current_user.slug, only_path: false)) %>"/>
    <meta property="og:title" content="Pesquisa De Satisfação Online - <%= current_user.company %>"/>
    <meta property="og:site_name" content="<%= current_user.company %>"/>
    <meta property="og:description" content="Responda Nossa Pesquisa De Satisfação Online e Nos Ajude a Melhorar!"/>
    <meta property="og:image" content="<%= URI(request.url) + current_user.logo.url %>"/>
    <meta property="og:type" content="website"/>

    <title>Satisfação 360</title>

    <%= favicon_link_tag "favicon.ico", :rel => "shortcut icon" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <script>
      var Chartkick = {"language": "pt-BR"};
    </script>
    <%= javascript_include_tag("https://www.google.com/jsapi", "chartkick", "data-turbolinks-track" => true) %>

    <%= csrf_meta_tags %>

    <link href="http://getbootstrap.com.br/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="backend">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo-backend.png", class: "navbar-brand"), root_path %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.questionaire_published? || current_user.answers.exists? %>
              <li class="visible-xs"><%= link_to "Respostas", backend_index_path %></li>
            <% end %>

            <li class="visible-xs"><%= link_to "Questionário", questions_path %></li>
            <li class="visible-xs"><%= link_to "Config. inicial", edit_user_path(current_user) %></li>
            <li><%= link_to "Minha conta", edit_user_path(current_user, only_account: true) %></li>
            <li><%= link_to "Sair do sistema", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-1 col-md-1 col-lg-1 sidebar">
          <ul class="nav nav-sidebar text-center">
            <% if current_user.questionaire_published? || current_user.answers.exists? %>
              <li>
                <%= link_to backend_index_path do %>
                  <i class="fa fa-line-chart"></i>
                  <br/>
                  Respostas
                <% end %>
              </li>
            <% end %>

            <li>
              <%= link_to questions_path do %>
                <i class="fa fa-list-ol"></i>
                <br/>
                Questionário
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                <i class="fa fa-cog"></i>
                <br/>
                Config. Inicial
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-sm-11 col-md-11 col-lg-11 main">
          <%= yield %>

          <hr style="<%= 'margin-top: 26px;' if controller_name == 'backend' %>"/>

          <%= render partial: "shared/copyright" %>
        </div>
      </div>
    </div>

    <script src="http://getbootstrap.com.br/assets/js/ie10-viewport-bug-workaround.js"></script>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name=viewport content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Sistema Para Pesquisa De Satisfação Online. Plano gratuito!"/>
    <meta name="author" content="Mário Marroquim"/>

    <title>Satisfação 360</title>

    <%= favicon_link_tag "favicon.ico", :rel => "shortcut icon" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>

    <link href="http://getbootstrap.com.br/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="devise">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-10 col-lg-offset-3 col-md-offset-2 col-sm-offset-1">
          <div class="text-center">
            <p>
              <%= link_to image_tag("logo-devise.png"), new_session_path(resource_name) %>
            </p>

            <p style="margin-top: 20px; margin-bottom: 26px;">
              <span class="text-bold">Sistema para pesquisa de satisfação online.</span>
              <br/>
              <span class="text-muted">
                Tenha uma visão 360 graus da satisfação dos seus clientes e melhore seu negócio.
                <br/>
                Puplique seu questionário online e acompanhe as respostas em tempo real.
              </span>
            </p>
          </div>

          <%= yield %>

          <%= render partial: "shared/copyright" %>
        </div>
      </div>
    </div>

    <script src="http://getbootstrap.com.br/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>